spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      accessKey: AKIARFOJQ5EGHQEHM4XK
      secretKey: 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
    s3:
      bucket: kijvideo
    region:
      static: ap-northeast-2
    stack:
      auto: false




